#!/bin/sh
# nohup python3 overfitting_pipeline.py --unique_name mel-wil_2 --load_model_path ../annotations/overfittings/overfits_weights/mel-wil_2_prev/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_mel-wil_2_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name mel-wil_4 --load_model_path ../annotations/overfittings/overfits_weights/mel-wil_4_prev/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_mel-wil_4_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name mel-wil_5 --load_model_path ../annotations/overfittings/overfits_weights/mel-wil_5_prev/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_mel-wil_5_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D2_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_D2_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name D3-1_L5_ori --load_model_path ./runs/pose/train/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_D3-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D3-2_L4_ori --load_model_path ./runs/pose/train/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_D3-2_L4_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D4-1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_D4-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C2_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C2_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C3-1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C3-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C5-1_L5_ori --load_model_path ../annotations/overfittings/overfits_weights/C5-1_L5_ori/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_C5-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name C6_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C6_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name mel-wil_1 --load_model_path ../annotations/overfittings/overfits_weights/mel-wil_1_prev/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_mel-wil_1_manual.out &

## DM + willistoni
# nohup python3 overfitting_pipeline.py --unique_name DM-wil_1 --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_DM-wil_1_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name DM-wil_2 --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_DM-wil_2_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name DM-wil_3 --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_DM-wil_3_manual.out ;
## DM + willistoni overtrain
# nohup python3 overfitting_pipeline.py --unique_name DM-wil_2 --load_model_path ../annotations/overfittings/overfits_weights/DM-wil_2_prev/weights/best.pt  --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_DM-wil_2_manual.out &
#nohup python3 overfitting_pipeline.py --unique_name DM-wil_3 --load_model_path ../annotations/overfittings/overfits_weights/DM-wil_3_prev/weights/best.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_DM-wil_3_manual.out ;

## D + L5
# nohup python3 overfitting_pipeline.py --unique_name mel-wil_1 --load_model_path ../annotations/overfittings/overfits_weights/mel-wil_1_prev/weights/best.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_mel-wil_1_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D5-1_L5_ori --load_model_path ../annotations/overfittings/overfits_weights/D5-1_L5_ori_old/weights/best.pt --gpu1 0 --gpu2 1  > ../annotations/overfittings/logs/train_overfits_D5-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name D5-1_L5_ori --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1  > ../annotations/overfittings/logs/train_overfits_D5-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name D3-1_L5_ori --load_model_path ./yolo11x-pose.pt    --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_D3-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D2_L5_ori --load_model_path ./yolo11x-pose.pt  --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_D2_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D3-2_L4_ori --load_model_path ./yolo11x-pose.pt    --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_D3-2_L4_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name D4-1_L5_ori --load_model_path ./yolo11x-pose.pt  --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_D4-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C1_L5_ori --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_C1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name C2_L5_ori --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_C2_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name C3-1_L5_ori --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_C3-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C5-1_L5_ori --load_model_path ./yolo11x-pose.pt  --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_C5-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name C6_L5_ori --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_C6_L5_ori_manual.out ;

## DM + whi overtrain
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_1 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_1_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_2 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_2_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_3 --load_model_path ./yolo11x-pose.pt --gpu1 0 --gpu2 1 > ../annotations/overfittings/logs/train_overfits_whi-DM_3_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_4 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_4_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_5 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_5_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_6 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_6_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name whi-DM_7 --load_model_path ./yolo11x-pose.pt --gpu1 2 --gpu2 3 > ../annotations/overfittings/logs/train_overfits_whi-DM_7_manual.out ;


# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C3-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C3-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/D3-1_L5_ori_overfit.csv  --start_frame 0  --end_frame 3000  --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/D3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D3-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D3-2_L4_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D3-2_L4_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D3-2_L4_ori.mov  --output_csv_path ./csvs/trajectory/D3-2_L4_ori_overfit.csv  --start_frame 0  --end_frame 3000 --max_id 4 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/D3-2_L4_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D3-2_L4_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D5-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D5-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D5-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/D5-1_L5_ori_overfit.csv  --start_frame 0  --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/D5-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D5-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D2_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D2_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D2_L5_ori.mov  --output_csv_path ./csvs/trajectory/D2_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/D2_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D2_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D4-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D4-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D4-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/D4-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/D4-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D4-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C1_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_C1_L5_ori.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C2_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C2_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C2_L5_ori.mov  --output_csv_path ./csvs/trajectory/C2_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C2_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C2_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C3-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C3-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C5-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C5-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C5-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C5-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C5-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C5-1_L5_ori.out ;
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C6_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C6_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C6_L5_ori.mov  --output_csv_path ./csvs/trajectory/C6_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/C6_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C6_L5_ori.out ;

### whi + DM
# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_1.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_1.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_1.mov  --output_csv_path ./csvs/trajectory/whi-DM_1_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_1/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_1.out ;
# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_2.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_2.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_2.mov  --output_csv_path ./csvs/trajectory/whi-DM_2_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_2/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_2.out ;
#nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_3.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_3.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_3.mov  --output_csv_path ./csvs/trajectory/whi-DM_3_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_3/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_3.out ;
# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_4.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_4.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_4.mov  --output_csv_path ./csvs/trajectory/whi-DM_4_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_4/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_4.out ;

# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_5.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_5.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_5.mov  --output_csv_path ./csvs/trajectory/whi-DM_5_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_5/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_5.out ;
# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_6.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_6.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_6.mov  --output_csv_path ./csvs/trajectory/whi-DM_6_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_3/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_6.out ;
nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_6.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_6.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_6.mov  --output_csv_path ./csvs/trajectory/whi-DM_6_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_6/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_6.out ;
# nohup python3 drosophila_predict.py --video_path ../video/whi-DM/whi-DM_7.avi --output_gif_path ../annotations/overfittings/gifs/overfit_whi-DM_7.gif --output_mov_path ../annotations/overfittings/movs/overfit_whi-DM_7.mov  --output_csv_path ./csvs/trajectory/whi-DM_7_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 6 --dist_thresh 30 --iou_thr 0.3 --conf 1e-3 --max_missing_frames 10  --model_path ../annotations/overfittings/overfits_weights/whi-DM_7ω/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_whi-DM_7.out ;