#!/bin/sh
# nohup python3 overfitting_pipeline.py --unique_name D5-1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_D5-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D2_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_D2_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name D3-1_L5_ori --load_model_path ./runs/pose/train/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_D3-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D3-2_L4_ori --load_model_path ./runs/pose/train/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_D3-2_L4_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name D4-1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_D4-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C2_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C2_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C3-1_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C3-1_L5_ori_manual.out ;
# nohup python3 overfitting_pipeline.py --unique_name C5-1_L5_ori --load_model_path ../annotations/overfittings/overfits_weights/C5-1_L5_ori/weights/best.pt  > ../annotations/overfittings/logs/train_overfits_C5-1_L5_ori_manual.out &
# nohup python3 overfitting_pipeline.py --unique_name C6_L5_ori --load_model_path ./yolo11x-pose.pt  > ../annotations/overfittings/logs/train_overfits_C6_L5_ori_manual.out ;
#nohup python3 drosophila_predict.py --video_path ../video/241227_original/C3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C3-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C3-1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_D3-1_L5_ori.csv  --start_frame 0  --end_frame 3000  --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/D3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D3-1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D3-2_L4_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D3-2_L4_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D3-2_L4_ori.mov  --output_csv_path ./csvs/trajectory/overfit_D3-2_L4_ori.csv  --start_frame 0  --end_frame 3000 --max_id 4 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/D3-2_L4_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D3-2_L4_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D5-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D5-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D5-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_D5-1_L5_ori.csv  --start_frame 0  --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/D5-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D5-1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D2_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D2_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D2_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_D2_L5_ori.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/D2_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D2_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/D4-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_D4-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_D4-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_D4-1_L5_ori.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/D4-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_D4-1_L5_ori.out &
nohup python3 drosophila_predict.py --video_path ../video/241227_original/C1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C1_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_C1_L5_ori.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C2_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C2_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C2_L5_ori.mov  --output_csv_path ./csvs/trajectory/overfit_C2_L5_ori.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C2_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C2_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C3-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C3-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C3-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C3-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C3-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C3-1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C5-1_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C5-1_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C5-1_L5_ori.mov  --output_csv_path ./csvs/trajectory/C5-1_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C5-1_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C5-1_L5_ori.out &
# nohup python3 drosophila_predict.py --video_path ../video/241227_original/C6_L5_ori.mov --output_gif_path ../annotations/overfittings/gifs/overfit_C6_L5_ori.gif --output_mov_path ../annotations/overfittings/movs/overfit_C6_L5_ori.mov  --output_csv_path ./csvs/trajectory/C6_L5_ori_overfit.csv  --start_frame 0 --end_frame 3000 --max_id 5 --dist_thresh 10 --iou_thr 0.3 --model_path ../annotations/overfittings/overfits_weights/C6_L5_ori/weights/best.pt --overlap_thresh 5 --head_tail_jump_thresh 40 > ../annotations/overfittings/logs/predict_overfit_C6_L5_ori.out &